name: KSAdmin
main: ksadmin.KSAdmin
version: 1.1.0

depend: [Multiverse-Core]

commands:
   cwarps:
      description: Accesses the Categorized Warps
      usage: /cwarps [Category] [Page Number]
   flower:
      description: Allows you to flower a radius
      usage: /flower <radius>
   ls:
      description: Lists Online Players
      usage: /ls
   msgOps:
      description: Messages Ops Through Discord
      usage: /msgOps <message>
      alias: [msgDiscord]
   quartz:
      description: Trades 10 NetherRack for 1 Quartz
      usage: /quartz
   shrug:
      description: Produces a shrug emoticon
      usage: /shrug

permissions:
  kadmin.*:
    description: Gives access to all kadmin commands
    children:
      kadmin.flower: true
  kadmin.flower:
    description: Bonemeals a radius
    default: op